name: Generate Podcast Feeds

on:
  push:
    branches:
      - main  # Adjust the branch name if necessary

jobs:
  build: 
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3
      
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
      
      - name: Install Dependencies 
        run: |
          python -m pip install --upgrade pip 
          pip install pyyaml
      
      - name: Run Feed Generator
        run: python feed.py
      
      - name: Configure Git
        run: |
          git config --global user.name 'github-actions'
          git config --global user.email 'github-actions@github.com'
      
      - name: Commit and Push Changes
        run: |
          git add .
          git commit -m "Modified Feed"
          git push
